apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: obc-dataconnection-init
rules:
  - apiGroups:
      - objectbucket.io/v1alpha
    resources:
      - ObjectBucketClaim
    verbs:
      - get
      - list
      - create
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - create
