kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-name: "Industrial edge workbench"
    opendatahub.io/notebook-image-desc: "Workbench for the industrial edge pattern"
  name: industrial-edge
  namespace: redhat-ods-applications
  labels:
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: "true"
    opendatahub.io/notebook-image: "true"
spec:
  lookupPolicy:
    local: true
  tags:
    - name: industrial-edge-v0.1.0
      annotations:
        opendatahub.io/notebook-python-dependencies: '[]'
        opendatahub.io/notebook-software: '[]'
        openshift.io/imported-from: 'quay.io/mmurakam/workbenches:industrial-edge-v0.1.0'
      from:
        kind: DockerImage
        name: 'quay.io/mmurakam/workbenches:industrial-edge-v0.1.0'
      generation: 2
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Source