apiVersion: odf.openshift.io/v1alpha1
kind: StorageSystem
metadata:
  finalizers:
    - storagesystem.odf.openshift.io
  name: ocs-storagecluster-storagesystem
  namespace: {{ .Values.ocs.namespace }}
spec:
  kind: storagecluster.ocs.openshift.io/v1
  name: ocs-storagecluster
  namespace: openshift-storage