---
kind: ExternalSecret
apiVersion: "external-secrets.io/v1beta1"
metadata:
  name: aws-connection-pipelines
  namespace: ml-development
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.global.secretStore.name }}
    kind: {{ .Values.global.secretStore.kind }}
  target:
    name: aws-connection-pipelines
    template:
      metadata:
        labels:
          opendatahub.io/dashboard: 'true'
          opendatahub.io/managed: 'true'
        annotations:
          opendatahub.io/connection-type: s3
          openshift.io/display-name: pipelines
      type: Opaque
  dataFrom:
    - extract:
      key: {{ .Values.awsPipelinesSecret.key }}
